version: "3.8"

services:
  message_service:
    image: mysticmail-message_service:latest
    ports:
      - "5000:5000"
    networks:
      - mysticmail_net

  user_service:
    image: mysticmail-user_service:latest
    ports:
      - "5001:5001"
    networks:
      - mysticmail_net
    depends_on:
      - db

  frontend:
    image: mysticmail-frontend:latest
    ports:
      - "8080:80"
    networks:
      - mysticmail_net

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - prometheus_data:/prometheus
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - "9090:9090"
    networks:
      - mysticmail_net

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3001:3000"
    volumes:
      - grafana_data:/var/lib/grafana
    depends_on:
      - prometheus
    networks:
      - mysticmail_net

  db:
    image: postgres:13
    environment:
      POSTGRES_DB: mysticmail
      POSTGRES_USER: mystic
      POSTGRES_PASSWORD: magicpass
    volumes:
      - mystic_pgdata:/var/lib/postgresql/data
    networks:
      - mysticmail_net

  adminer:
    image: adminer
    restart: always
    ports:
      - "8081:8080"
    networks:
      - mysticmail_net



  kong-db:
    image: postgres:13
    environment:
      POSTGRES_USER: kong
      POSTGRES_DB: kong
      POSTGRES_PASSWORD: kong
    volumes:
      - kong_db:/var/lib/postgresql/data
    networks:
      - mysticmail_net

  kong:
    image: kong:3.4
    environment:
      KONG_DATABASE: postgres
      KONG_PG_HOST: kong-db
      KONG_PG_PASSWORD: kong
      KONG_PROXY_ACCESS_LOG: /dev/stdout
      KONG_ADMIN_ACCESS_LOG: /dev/stdout
      KONG_PROXY_ERROR_LOG: /dev/stderr
      KONG_ADMIN_ERROR_LOG: /dev/stderr
      KONG_ADMIN_LISTEN: 0.0.0.0:8001
    depends_on:
      - kong-db
    ports:
      - "8000:8000"   # public API gateway
      - "8001:8001"   # admin API
    networks:
      - mysticmail_net

  konga:
    image: pantsel/konga:latest
    environment:
      NODE_ENV: development
    ports:
      - "1337:1337"
    networks:
      - mysticmail_net


  # kong-migrations:
  #   image: kong:3.4
  #   command: kong migrations bootstrap
  #   environment:
  #     KONG_DATABASE: postgres
  #     KONG_PG_HOST: kong-db
  #     KONG_PG_PASSWORD: kong
  #   depends_on:
  #     - kong-db
  #   networks:
  #     - mysticmail_net
  #   deploy:
  #     restart_policy:
  #       condition: on-failure


networks:
  mysticmail_net:
    external: true
    attachable: true

volumes:
  prometheus_data:
  grafana_data:
  mystic_pgdata:
  kong_db:


