version: "3.8"

services:
  message_service:
    image: mysticmail-message_service:latest
    ports:
      - "5000:5000"

  user_service:
    image: mysticmail-user_service:latest
    ports:
      - "5001:5001"

  frontend:
    image: mysticmail-frontend:latest
    ports:
      - "8080:80"
