version: "3.8"

services:
  message_service:
    build: ./message_service
    ports:
      - "5000:5000"
    container_name: message_service

  user_service:
    build: ./user_service
    ports:
      - "5001:5001"
    container_name: user_service

  frontend:
    build: ./frontend
    ports:
      - "8080:80"
    container_name: frontend
