global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'message_service'
    static_configs:
      - targets: ['message_service:5005']

  - job_name: 'user_service'
    static_configs:
      - targets: ['user_service:5001']
  - job_name: 'notification_service'
    static_configs:
      - targets: ['notification_service:5010']
